<?php

namespace ComicBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * CharactrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharactrRepository extends EntityRepository
{

    /**
     * @param array $filters
     * @return array
     */
    public function listCharactrs(array $filters = [])
    {
        $alias = 'ch';
        $qb = $this->createQueryBuilder($alias)->select($alias);


        //TODO: Ver  si funciona el filtro:
        if (isset($filters['comic'])) {

            $aliasComic = 'c';
            $qb ->join("$alias.comics", "$aliasComic")
                ->andWhere($qb->expr()->eq("$aliasComic.id", ':comic'))
                ->setParameter('comic', $filters['comic']);
        }
        return $qb->getQuery()->getResult();
    }


}
