<?php

namespace ComicBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * LibraryListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibraryListRepository extends EntityRepository
{
    /**
     * @param array $filters
     * @return array
     */
    public function listLibraryLists(array $filters = [])
    {
        $alias = 'll';
        $qb = $this->createQueryBuilder($alias)->select($alias);


        return $qb->getQuery()->getResult();
    }
}
