<?php

namespace ComicBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * ReadListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReadListRepository extends EntityRepository
{
    /**
     * @param array $filters
     * @return array
     */
    public function listReadLists(array $filters = [])
    {
        $alias = 'rl';
        $qb = $this->createQueryBuilder($alias)->select($alias);


        return $qb->getQuery()->getResult();
    }
}
