<?php

namespace ComicBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * ToReadListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToReadListRepository extends EntityRepository
{
}
