<?php

namespace ComicBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param array $filters
     * @return array
     */
    public function listUsers(array $filters = [])
    {
        $alias = 'u';

        $qb = $this->createQueryBuilder($alias)->select($alias) ;


        return $qb->getQuery()->getResult();

    }
}
